raw_table_name: prod_dsexp_mlstore.third_party_capture.tpc_raw_data_table

feature_table_name: prod_dsexp_mlstore.third_party_capture.tpc_feature_table

severity_columns:
  -  boot_opens
  -  doors_open
  -  front_bonnet_severity
  -  front_left_severity
  -  front_right_severity
  -  front_severity
  -  left_back_seat_severity
  -  left_front_wheel_severity
  -  left_mirror_severity
  -  left_rear_wheel_severity
  -  left_roof_severity
  -  left_severity
  -  left_underside_severity
  -  lights_damaged
  -  load_area_severity
  -  panel_gaps
  -  radiator_damaged
  -  rear_left_severity
  -  rear_right_severity
  -  rear_severity
  -  rear_window_damage_severity
  -  right_back_seat_severity
  -  right_front_wheel_severity
  -  right_mirror_severity
  -  right_rear_wheel_severity
  -  right_roof_severity
  -  right_severity
  -  right_underside_severity
  -  roof_damage_severity
  -  sharp_edges
  -  underbody_damage_severity
  -  wheels_damaged
  -  windscreen_damage_severity

tp_fp_columns:
  -  deployed_airbags
  -  engine_damage
  -  exhaust_damaged
  -  engine_capacity
  -  damage_assessed
  -  not_on_mid
  -  vehicle_unattended
  -  body_key
  -  engine_capacity
  -  right_hand_drive
  -  number_of_doors
  -  wheels_damaged
  -  lights_damaged
  -  number_of_seats
  -  colour
  -  mileage
  -  driveable_damage_assessment
  -  vehicle_value
  -  vehicle_age
  -  body_key_01
  -  body_key_02
  -  body_key_03
  -  body_key_04
  -  fuel_type_01 
  -  fuel_type_02

constant_cols:
  -  bonnet_submerged
  -  engine_running_in_water
  -  water_ingress_within_engine
  -  side_panel_damage
  -  structural_damage
  -  is_high_value_vehicle
  -  theft_damage
  -  event_identity
  -  claim_id
  -  vehicle_registration
  -  market_value
  -  registration_number
  -  policy_reference
  -  vehicle_reg
  -  abi_model_code
  -  quote_iteration_id
  -  gross_amount 
  -  event_identity 
  -  policy_number 
  -  incident_type 
  -  insurance_id

ordered_columns:
  - claim_number
  - vehicle_unattended
  - not_on_mid
  - fp_not_on_mid
  - tp_not_on_mid
  - claim_item_type
  - notification_date
  - insurer_name
  - first_party_confirmed
  - vehicle_kept_at_postcode
  - year_of_manufacture
  - manufacturer_description
  - impact_speed_range
  - impact_speed_unit
  - incident_date
  - incident_cause_description
  - incident_sub_cause_description
  - incident_location_uk_country
  - weather_conditions
  - reported_date
  - notification_method
  - road_conditions
  - assessment_category
  - driveable_damage_assessment
  - fp_driveable_damage_assessment
  - tp_driveable_damage_assessment
  - da_dr
  - da_dtl
  - da_utl
  - da_ur
  - da_o
  - intervention_outcome
  - right_hand_drive
  - fp_right_hand_drive
  - tp_right_hand_drive
  - vehicle_value
  - fp_vehicle_value
  - tp_vehicle_value
  - fp_body_key
  - tp_body_key
  - fp_number_of_doors
  - tp_number_of_doors
  - number_of_doors
  - number_of_seats
  - fp_number_of_seats
  - tp_number_of_seats
  - colour
  - fp_colour
  - tp_colour
  - engine_capacity
  - fp_engine_capacity
  - tp_engine_capacity
  - mileage
  - fp_mileage
  - tp_mileage
  - impact_speed
  - damage_recorded
  - damage_assessed
  - fp_damage_assessed
  - tp_damage_assessed
# - fuel_key  ##Not in API request
  - fuel_type_01
  - fuel_type_02
  - fp_fuel_type_01
  - fp_fuel_type_02
  - tp_fuel_type_01
  - tp_fuel_type_02
  - body_key
  - body_key_01
  - body_key_02
  - body_key_03
  - body_key_04
  - fp_body_key_01
  - fp_body_key_02
  - fp_body_key_03
  - fp_body_key_04
  - tp_body_key_01
  - tp_body_key_02
  - tp_body_key_03
  - tp_body_key_04
  - time_to_notify
  - vehicle_age
  - fp_vehicle_age
  - tp_vehicle_age
  - notified_day_of_week
  - notified_day
  - notified_month
  - notified_year
  - incident_day_of_week
  - incident_day
  - postcode_area
  - damage_sev_total
  - damage_sev_count
  - damage_sev_mean
  - damage_sev_max
  - fp_front_severity
  - tp_front_severity
  - fp_front_bonnet_severity
  - tp_front_bonnet_severity
  - fp_front_left_severity
  - tp_front_left_severity
  - fp_front_right_severity
  - tp_front_right_severity
  - fp_left_severity
  - tp_left_severity
  - fp_left_back_seat_severity
  - tp_left_back_seat_severity
  - fp_left_front_wheel_severity
  - tp_left_front_wheel_severity
  - fp_left_mirror_severity
  - tp_left_mirror_severity
  - fp_left_rear_wheel_severity
  - tp_left_rear_wheel_severity
  - fp_left_underside_severity
  - tp_left_underside_severity
  - fp_rear_severity
  - tp_rear_severity
  - fp_rear_left_severity
  - tp_rear_left_severity
  - fp_rear_right_severity
  - tp_rear_right_severity
  - fp_rear_window_damage_severity
  - tp_rear_window_damage_severity
  - fp_right_severity
  - tp_right_severity
  - fp_right_back_seat_severity
  - tp_right_back_seat_severity
  - fp_right_front_wheel_severity
  - tp_right_front_wheel_severity
  - fp_right_mirror_severity
  - tp_right_mirror_severity
  - fp_right_rear_wheel_severity
  - tp_right_rear_wheel_severity
  - fp_right_roof_severity
  - tp_right_roof_severity
  - fp_right_underside_severity
  - tp_right_underside_severity
  - fp_roof_damage_severity
  - tp_roof_damage_severity
  - fp_underbody_damage_severity
  - tp_underbody_damage_severity
  - fp_windscreen_damage_severity
  - tp_windscreen_damage_severity
  - fp_boot_opens
  - tp_boot_opens
  - fp_deployed_airbags
  - tp_deployed_airbags
  - fp_doors_open
  - tp_doors_open
  - fp_engine_damage
  - tp_engine_damage
  - fp_exhaust_damaged
  - tp_exhaust_damaged
  - fp_left_roof_severity
  - tp_left_roof_severity
  - fp_lights_damaged
  - tp_lights_damaged
  - fp_load_area_severity
  - tp_load_area_severity
  - fp_panel_gaps
  - tp_panel_gaps
  - fp_radiator_damaged
  - tp_radiator_damaged
  - fp_sharp_edges
  - tp_sharp_edges
  - fp_vehicle_unattended
  - tp_vehicle_unattended
  - fp_wheels_damaged
  - tp_wheels_damaged
  - payment_category
  - CaptureSuccess_AdrienneVersion
  - inc_tot_tppd