workspaces:
  'adb-7739692825668627.7.azuredatabricks.net': prod_modelbuild_
  'adb-46486507102030.10.azuredatabricks.net': prod_modelpromotion_
  'adb-1657058261328338.18.azuredatabricks.net': prod_modeldeployment_

input_data:
  catalog_suffix: mlstore
  schema: geo_indices
  name: postcode_feature_table

scored_data:
  catalog_suffix: mlscoring
  schema: geo_indices
  baseline: baseline_pcd_scores
  latest_baseline: latest_baseline_pcd_scores
  latest: latest_scoring_pcd_output

model:
  catalog_suffix: mlstore
  schema: geo_indices
  names:
    - INC_TOT_AD
    - INC_TOT_FIRE
    - INC_TOT_THEFT
    - INC_TOT_TPI
    - INC_TOT_TPPD
    - INC_TOT_WS
    - NUM_CLM_AD
    - NUM_CLM_FIRE
    - NUM_CLM_THEFT
    - NUM_CLM_TPI
    - NUM_CLM_TPPD
    - NUM_CLM_WS
    - Total_INC_TOT
    - Total_NUM_CLM

  alias: Champion


unwanted_columns:
  - PPTV_RISK_PCODE
  - P_EXTERNAL_REF
  - PPT_START_DATE
  - PPT_END_DATE
  - PPT_UNIQUE_REF
  - PPT_PRODUCT_LEVEL
  - PPTV_VALUE
  - PPTV_YEAR
  - CLM_NUMBER
  - INCIDENT_DT
  - INCIDENT_DATE
  - Policy length total
  - Exposure days during claims period
  - oseast1m
  - osnrth1m
  - oa11
  - oa11_
  - laua
  - ctry
  - rgn
  - park
  - lsoa11
  - msoa11
  - bua11
  - ru11ind
  - imd
  - InUse
  - Output_Area
  - Postcode_region
  - Policy_length_total
  - Exposure_weighting
  - Exposure_days_during_claims_period
  

data_loader_cols:
  - _rescued_data
  - source_file_path
  - source_file_modified_date
  - source_load_date