rename_map:
  daysinrepair: days_in_repair
  incidentcausedescription: incident_cause_description
  bootopens: boot_opens
  deployedairbags: deployed_airbags
  front: front_severity
  frontbonnet: front_bonnet_severity
  frontleft: front_left_severity
  frontright: front_right_severity
  left: left_severity
  leftbackseat: left_back_seat_severity
  leftfrontwheel: left_front_wheel_severity
  leftmirror: left_mirror_severity
  leftrearwheel: left_rear_wheel_severity
  leftunderside: left_underside_severity
  rear: rear_severity
  rearleft: rear_left_severity
  rearright: rear_right_severity
  rearwindowdamage: rear_window_damage_severity
  right: right_severity
  rightbackseat: right_back_seat_severity
  rightfrontwheel: right_front_wheel_severity
  rightmirror: right_mirror_severity
  rightrearwheel: right_rear_wheel_severity
  rightroof: right_roof_severity
  rightunderside: right_underside_severity
  roofdamage: roof_damage_severity
  underbodydamage: underbody_damage_severity
  windscreendamage: windscreen_damage_severity
  doorsopen: doors_open
  driveable: driveable_damage_assessment
  lightsdamaged: lights_damaged
  panelgaps: panel_gaps
  sharpedges: sharp_edges
  wheelsdamaged: wheels_damaged
  doors: number_of_doors
  enginecapacity: engine_capacity
  seats: number_of_seats
  value: vehicle_value
  da_dr: da_dr
  da_dtl: da_dtl
  da_utl: da_utl
  da_ur: da_ur
  da_o: da_o
  timetonotify: time_to_notify
  vehicleage: vehicle_age
  bodykey_01: body_key_01
  bodykey_02: body_key_02
  bodykey_03: body_key_03
  bodykey_04: body_key_04
  nature_ph: first_party_confirmed
  notified_dow: notified_day_of_week
  notified_day: notified_day
  notified_month: notified_month
  notified_year: notified_year
  incident_dow: incident_day_of_week
  incident_day: incident_day
  postcodearea: postcode_area
  damagesev_total: damage_sev_total
  damagesev_count: damage_sev_count
  damagesev_mean: damage_sev_mean
  damagesev_max: damage_sev_max

fp_tp_columns:
  - boot_opens
  - deployed_airbags
  - front_severity
  - front_bonnet_severity
  - front_left_severity
  - front_right_severity
  - left_severity
  - left_back_seat_severity
  - left_front_wheel_severity
  - left_mirror_severity
  - left_rear_wheel_severity
  - left_underside_severity
  - rear_severity
  - rear_left_severity
  - rear_right_severity
  - rear_window_damage_severity
  - right_severity
  - right_back_seat_severity
  - right_front_wheel_severity
  - right_mirror_severity
  - right_rear_wheel_severity
  - right_roof_severity
  - right_underside_severity
  - roof_damage_severity
  - underbody_damage_severity
  - windscreen_damage_severity
  - doors_open
  - driveable_damage_assessment
  - lights_damaged
  - panel_gaps
  - sharp_edges
  - wheels_damaged
  - number_of_doors
  - engine_capacity
  - number_of_seats
  - vehicle_value
  - vehicle_age
  - body_key_01
  - body_key_02
  - body_key_03
  - body_key_04

ttr_target_column: days_in_repair

cat_features:
  - insurer_name
  - incident_cause_description
  - postcode_area
  - tp_body_key
  - fp_body_key
  - notification_method
  - incident_sub_cause_description
  - impact_speed_range
  - impact_speed_unit
  - tp_colour
  - incident_uk_country
  - road_conditions
  - weather_conditions

num_features:
  - capturesuccess_adrienneversion
  - year_of_manufacture
  - tp_engine_capacity
  - tp_number_of_doors
  - tp_boot_opens
  - tp_right_hand_drive
  - tp_doors_open
  - tp_not_on_mid
  - tp_vehicle_unattended
  - tp_wheels_damaged
  - fp_deployed_airbags
  - tp_deployed_airbags
  - tp_lights_damaged
  - tp_front_severity
  - tp_front_bonnet_severity
  - tp_front_left_severity
  - tp_front_right_severity
  - tp_left_severity
  - tp_left_back_seat_severity
  - tp_left_front_wheel_severity
  - tp_left_mirror_severity
  - tp_left_rear_wheel_severity
  - tp_left_roof_severity
  - tp_left_underside_severity
  - tp_load_area_severity
  - tp_rear_severity
  - tp_rear_left_severity
  - tp_rear_right_severity
  - tp_rear_window_damage_severity
  - tp_right_severity
  - tp_right_back_seat_severity
  - tp_right_front_wheel_severity
  - tp_right_mirror_severity
  - tp_right_rear_wheel_severity
  - tp_right_roof_severity
  - tp_right_underside_severity
  - tp_roof_damage_severity
  - tp_underbody_damage_severity
  - tp_windscreen_damage_severity
  - impact_speed
  - time_to_notify
  - notified_day_of_week
  - notified_day
  - notified_month
  - notified_year
  - incident_day_of_week
  - incident_day
  - fp_vehicle_age
  - damage_recorded
  - tp_damage_assessed
  - damage_sev_total
  - damage_sev_count
  - damage_sev_mean
  - damage_sev_max
  - fp_boot_opens
  - fp_doors_open
  - fp_engine_capacity
  - fp_front_bonnet_severity
  - fp_front_left_severity
  - fp_front_right_severity
  - fp_front_severity
  - fp_left_back_seat_severity
  - fp_left_front_wheel_severity
  - fp_left_mirror_severity
  - fp_left_rear_wheel_severity
  - fp_left_roof_severity
  - fp_left_severity
  - fp_left_underside_severity
  - fp_lights_damaged
  - fp_load_area_severity
  - fp_number_of_doors
  - fp_number_of_seats
  - fp_panel_gaps
  - fp_radiator_damaged
  - fp_rear_left_severity
  - fp_rear_right_severity
  - fp_rear_severity
  - fp_rear_window_damage_severity
  - fp_right_back_seat_severity
  - fp_right_front_wheel_severity
  - fp_right_mirror_severity
  - fp_right_rear_wheel_severity
  - fp_right_roof_severity
  - fp_right_severity
  - fp_right_underside_severity
  - fp_roof_damage_severity
  - fp_sharp_edges
  - fp_underbody_damage_severity
  - fp_vehicle_value
  - fp_wheels_damaged
  - fp_windscreen_damage_severity
  - tp_mileage
  - tp_driveable_damage_assessment

date_columns: 
  - notification_date
  - incident_date

tpc_target_column: inc_tot_tppd

cat_ohe:
  - insurer_name
  - incident_cause_description
  - postcode_area
  - notification_method
  - incident_sub_cause_description
  - tp_colour
  - incident_uk_country
  - road_conditions
  - weather_conditions

num_std:
  - fp_deployed_airbags
  - fp_number_of_doors
  - fp_engine_capacity
  - fp_number_of_seats
  - fp_vehicle_value
  - tp_deployed_airbags
  - tp_number_of_doors
  - tp_engine_capacity
  - tp_lights_damaged
  - tp_mileage
  - year_of_manufacture
  - fp_front_severity
  - tp_front_severity
  - fp_front_bonnet_severity
  - tp_front_bonnet_severity
  - fp_front_left_severity
  - tp_front_left_severity
  - fp_front_right_severity
  - tp_front_right_severity
  - fp_left_severity
  - tp_left_severity
  - fp_left_back_seat_severity
  - tp_left_back_seat_severity
  - fp_left_front_wheel_severity
  - tp_left_front_wheel_severity
  - fp_left_mirror_severity
  - tp_left_mirror_severity
  - fp_left_rear_wheel_severity
  - tp_left_rear_wheel_severity
  - fp_left_roof_severity
  - tp_left_roof_severity
  - fp_left_underside_severity
  - tp_left_underside_severity
  - fp_load_area_severity
  - tp_load_area_severity
  - fp_rear_severity
  - tp_rear_severity
  - fp_rear_left_severity
  - tp_rear_left_severity
  - fp_rear_right_severity
  - tp_rear_right_severity
  - fp_rear_window_damage_severity
  - tp_rear_window_damage_severity
  - fp_right_severity
  - tp_right_severity
  - fp_right_back_seat_severity
  - tp_right_back_seat_severity
  - fp_right_front_wheel_severity
  - tp_right_front_wheel_severity
  - fp_right_mirror_severity
  - tp_right_mirror_severity
  - fp_right_rear_wheel_severity
  - tp_right_rear_wheel_severity
  - fp_right_roof_severity
  - tp_right_roof_severity
  - fp_right_underside_severity
  - tp_right_underside_severity
  - fp_roof_damage_severity
  - tp_roof_damage_severity
  - fp_underbody_damage_severity
  - tp_underbody_damage_severity
  - fp_windscreen_damage_severity
  - tp_windscreen_damage_severity
  - impact_speed
  - time_to_notify
  - notified_day_of_week
  - notified_day
  - notified_month
  - notified_year
  - incident_day_of_week
  - incident_day
  - fp_vehicle_age
  - tp_body_key_04
  - tp_damage_assessed
  - damage_sev_total
  - damage_sev_count
  - damage_sev_mean
  - damage_sev_max


cat_impute:
  - postcode_area
  - incident_sub_cause_description
  - incident_uk_country
  - incident_cause_description
  - insurer_name
  - notification_method
  - road_conditions
  - tp_colour
  - weather_conditions

num_impute:
  - fp_boot_opens
  - fp_deployed_airbags
  - fp_number_of_doors
  - fp_doors_open
  - fp_engine_capacity
  - vehicle_kept_at_postcode
  - fp_lights_damaged
  - fp_number_of_seats
  - fp_vehicle_value
  - fp_wheels_damaged
  - tp_boot_opens
  - tp_deployed_airbags
  - tp_number_of_doors
  - tp_doors_open
  - tp_engine_capacity
  - tp_right_hand_drive
  - tp_lights_damaged
  - tp_mileage
  - tp_not_on_mid
  - tp_vehicle_unattended
  - year_of_manufacture
  - tp_wheels_damaged
  - tp_front_severity
  - tp_front_bonnet_severity
  - tp_front_left_severity
  - tp_front_right_severity
  - tp_left_severity
  - tp_left_back_seat_severity
  - tp_left_front_wheel_severity
  - tp_left_mirror_severity
  - tp_left_rear_wheel_severity
  - tp_left_roof_severity
  - tp_left_underside_severity
  - tp_load_area_severity
  - tp_rear_severity
  - tp_rear_left_severity
  - tp_rear_right_severity
  - tp_rear_window_damage_severity
  - tp_right_severity
  - tp_right_back_seat_severity
  - tp_right_front_wheel_severity
  - tp_right_mirror_severity
  - tp_right_rear_wheel_severity
  - tp_right_roof_severity
  - tp_right_underside_severity
  - tp_roof_damage_severity
  - tp_underbody_damage_severity
  - tp_windscreen_damage_severity
  - impact_speed
  - da_dr
  - da_dtl
  - da_utl
  - da_ur
  - da_o
  - time_to_notify
  - notified_day_of_week
  - notified_day
  - notified_month
  - notified_year
  - incident_day_of_week
  - incident_day
  - fp_vehicle_age
  - fp_body_key_01
  - tp_body_key_01
  - fp_body_key_02
  - tp_body_key_02
  - fp_body_key_03
  - tp_body_key_03
  - fp_body_key_04
  - tp_body_key_04
  - damage_recorded
  - tp_damage_assessed
  - damage_sev_total
  - damage_sev_count
  - damage_sev_mean
  - damage_sev_max

































training_data_table:
  catalog_suffix: mlstore
  schema: third_party_capture
  name:   ttr_df

tpc_training_data_table:
  catalog_suffix: mlstore
  schema: third_party_capture
  name:   ttr_df

trained_model:
  catalog_suffix: mlstore
  schema: geo_indices

space:
  max_depth: 
    min: 1
    max: 5 # 20
  eta:
    min: 0.01
    max: 0.3
  objective: reg:squarederror
  eval_metric: rmse

cv_space:
  max_depth: 
    - 1
    - 3
    - 5
  learning_rate:
    - 0.01
    - 0.1
    - 0.2
    - 0.3
  objective: reg:squarederror
  eval_metric: rmse

recreate_endpoint: true

remove_champion_alias: false

remove_challenger_alias: false