channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=23.2.1
- pip:
  - mlflow==2.13.1
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - lightgbm==4.3.0
  - lz4==4.3.2
  - matplotlib==3.7.2
  - pandas==1.5.3
  - psutil==5.9.0
  - pyarrow==14.0.1
  - scikit-learn==1.3.0
name: mlflow-env
